[[section-design-decisions]]
== Decisiones de Arquitectura

.*Restricciones*
* Uso de Solid y de sus pods para crear una aplicación basada en un almacenamiento descentralizado de los datos, a diferencia del usual almacenamiento centralizado que utilizan la mayoría de sistemas y aplicaciones.
* Aplicación debe ser soportada por dispositivos móviles.

.*Problemas*
* Uso de tecnologías que nunca antes habíamos visto(Ej: Solid).
* Debido a la multitud de lenguajes de programación existentes, se ha tenido que buscar uno que soportara Solid y que fuera bastante flexible.
* Dificultad a la hora de decidirnos por el idioma de documentación y desarrollo de la aplicación. 


.*Consecuencias*
* Debido al uso de nuevas tecnologías, hemos tenido que documentarnos y ejecutar una serie de proyectos ejemplo para poder entender mejor todo aquello que, hasta hace nada, era desconocido para nosotros.
* Puesto que el lenguaje de programación es de libre elección, el equipo de desarrollo se ha reunido para elegir uno que fuera conocido por todos los integrantes, y que a su vez fuera bastante flexible y extendido. A su vez, este lenguaje ha de ser compatible con Solid.
* La deción del idioma de documentación e implementación ha resultado complicado. A pesar de decidirnos por el Español por simplicidad, somos conscientes de que es una decisión arriesgada, puesto que sería difícil presentar esta aplicación a nivel internacional.


.Alternativas Descartadas
* Uso de cualquier sistema que ofrezca un almacenamiento de datos de tipo centralizado, puesto que una de las restricciones es el uso de Solid y sus pods para un almacenamiento de datos descentralizado.
* Uso de cualquier framework de programación que no sea React Native. Esto ha sido una decisión tomada, ya que no existía ninguna restricción en este aspecto.

.*Decisiones Tomadas*
* Uso de JavaScript, debido a que es un lenguaje que ofrece muchas posibilidades y tiene una alta compatibilidad con Solid. Además de ésto, JavaScript es un lenguaje conocido por todo el equipo de desarrollo.
* Uso de React Native como framework de programación. React Native nos viene muy bien debido a que usamos JavaScript como lenguaje de programación, y porque creemos que nos puede facilitar bastante el desarrollo de la aplicación.
* Para la geolocalización haremos uso de la api de google maps, muy extendida y fiable.
* Sistema desplegable en contenedores docker y heroku.
* Uso de bootstrap para la elaboración de hojas de estilo, de manera la aplicación resulte más agradable a la vista del usuario.
